project_name: j4ne
project_root: /opt/{{ project_name }}
application_path: "{{ project_root }}"
virtualenv_path: "{{ project_root }}/env"
project_repo: https://github.com/japherwocky/pforex.git
project_uid: 1313
project_gid: 1313

system_packages:
  - git
  - ntp
  - build-essential 
  - python-virtualenv
  - python-pip
  - python-dev
  - nginx